version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile && npm install --global gulp

      - run:
          name: Dist
          command: gulp dist

      - run:
          name: Unit Tests
          command: gulp unit --nobuild --headless

      - run:
          name: Unit Tests
          command: gulp integration --nobuild --headless
workflows:
    build-and-test:
      jobs:
        - build-and-test
