version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:
  amphtml-executor:
    docker:
      - image: circleci/node:lts-browsers

jobs:
  dist:
    executor:
      name: amphtml-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Dist
          command: npx gulp dist
      - 

  unit-tests:
    executor: amphtml-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
        name: Unit Tests
        command: npx gulp unit --nobuild --headless

  inregration-tests:
    executor: amphtml-executor
    - steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Integration Tests
          command: npx gulp integration --nobuild --headless
        

workflows:
    build-and-test:
      jobs:
        - dist
        - unit-tests:
            requires:
              - dist
        - integration-tests:
            requires:
              - dist
