version: 2.1
orbs:
  node: circleci/node@latest
jobs:
  build-and-test:
    executor:
      name: node/lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          steps:
          - run:
              name: Dist
              command: gulp dist

          - run:
              name: Unit Tests
              command: gulp unit --nobuild --headless

          - run:
              name: Unit Tests
              command: gulp integration --nobuild --headless
workflows:
    build-and-test:
      jobs:
        - build-and-test
