name: Release tagger
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'tagger action (promote | rollback)'
        required: true
      head:
        description: 'head AMP version'
        required: true
      base:
        description: 'base AMP version'
        required: true
      channel:
        description: 'release channel (beta-opt-in | beta-percent | stable | lts)'
        required: true
      sha:
        description: 'commit sha'
        required: true
permissions:
  contents: read

jobs:
  tagger:
    environment: release_tagger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: lts/*
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: bash ./.github/workflows/install_dependencies.sh
      - name: Run tagger
        run: |
          node ./build-system/release-tagger/index.js \
            --action ${{ github.event.inputs.action }} \
            --head ${{ github.event.inputs.head }} \
            --base ${{ github.event.inputs.base }} \
            --channel ${{ github.event.inputs.channel }} \
            --sha ${{ github.event.inputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
